### ISSUE TITLE
Repository dead?

### ISSUE THREAD

**Issue by Tehnix** [yav/colorize-haskell#3]
I see there hasn't been an update in quite a while, and wanted to reach out, because I was considering taking over maintenance if you don't find you have time for this anymore. This way we can get it on stackage etc.

Let me know your thoughts!

**Comment by yav** [comment]
Hi,

the repository is not dead---it is just that this is a small utility that hasn't really needed to be changed.   If you found a bug, or would like some feature, could you please make a ticket?
